export const LOGIN = 'LOGIN'
export const SWAP_STATE = 'SWAP_STATE'
export const LOAD_IDEAS = 'LOAD_IDEAS'
export const SORT_DOWN_IDEAS = 'SORT_DOWN_IDEAS'
export const SORT_UP_IDEAS = 'SORT_UP_IDEAS'
